version: '3'
services:
    backend:
        container_name: darksouls-backend
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
            args:
                WAR_NAME: darksouls-explorer-backend
        ports:
            - "8080:8080"
            - "8000:8000"
        environment:
            # JDBC
            - spring.datasource.url=jdbc:mysql://db:3306/data
            - spring.datasource.username=user
            - spring.datasource.password=password
            # Neo4J
            - spring.neo4j.uri=bolt://graph-db:7687
            - spring.neo4j.authentication.username=neo4j
            - spring.neo4j.authentication.password=secret