FROM neo4j:latest

# Install git
RUN apt update
RUN apt-get -y install git

# Create import directory
WORKDIR /usr/src/import

# Clone data source
ENV USER=Bernardo-MG
ENV REPOSITORY=darksouls-explorer-dataset
ENV BRANCH=develop
ADD https://api.github.com/repos/$USER/$REPOSITORY/git/refs/heads/$BRANCH version.json
RUN git clone -b $BRANCH https://github.com/$USER/$REPOSITORY.git /ds

COPY /docker/load_data.sh /load_data.sh

CMD sh /load_data.sh
