FROM neo4j:latest

# Install git
RUN apt update
RUN apt-get -y install git

# Clone data source
RUN git clone -b develop https://github.com/Bernardo-MG/darksouls-explorer-dataset.git /ds
RUN cp -r /ds/darksouls_1/data /var/lib/neo4j/import/data

# Health check
HEALTHCHECK --interval=30s --timeout=3s --retries=5 \
  CMD perl -MIO::Socket::INET -e 'exit(! defined( IO::Socket::INET->new("localhost:7687")))'
