CREATE (i:Item:Weapon {name: 'Sword'});
CREATE (p:WeaponUpgradePath {name: 'Physical'});
CREATE (p:WeaponUpgradePath {name: 'Magic'});
MATCH (w:Weapon {name: 'Sword'}), (p:WeaponUpgradePath {name: 'Physical'}) MERGE (w)-[:HAS_LEVEL]->(p);
CREATE (l:WeaponLevel {name: 'Sword Physical', weapon: 'Sword', path: 'Physical', level: 0, physicalDamage: 10, magicDamage: 11, fireDamage: 12, lightningDamage: 13});
CREATE (l:WeaponLevel {name: 'Sword Physical 1', weapon: 'Sword', path: 'Physical', level: 1, physicalDamage: 20, magicDamage: 21, fireDamage: 22, lightningDamage: 23});
CREATE (l:WeaponLevel {name: 'Sword Physical 2', weapon: 'Sword', path: 'Physical', level: 2, physicalDamage: 30, magicDamage: 31, fireDamage: 32, lightningDamage: 33});
CREATE (l:WeaponLevel {name: 'Sword Physical 3', weapon: 'Sword', path: 'Physical', level: 3, physicalDamage: 40, magicDamage: 41, fireDamage: 42, lightningDamage: 43});
CREATE (l:WeaponLevel {name: 'Sword Physical 4', weapon: 'Sword', path: 'Physical', level: 4, physicalDamage: 50, magicDamage: 51, fireDamage: 52, lightningDamage: 53});
CREATE (l:WeaponLevel {name: 'Sword Magic', weapon: 'Sword', path: 'Magic', level: 0, physicalDamage: 10, magicDamage: 11, fireDamage: 12, lightningDamage: 13});
MATCH (l:WeaponLevel), (m:WeaponLevel) WHERE m.path = l.path AND m.level = l.level + 1 MERGE (l)-[:NEXT]->(m);
MATCH (l:WeaponLevel {path: 'Physical', level: 4}), (m:WeaponLevel {path: 'Magic', level: 0}) MERGE (l)-[:NEXT]->(m);
MATCH (p:WeaponUpgradePath {name: 'Physical'}), (l:WeaponLevel {path: 'Physical'}) MERGE (p)-[:HAS_LEVEL]->(l);
MATCH (p:WeaponUpgradePath {name: 'Magic'}), (l:WeaponLevel {path: 'Magic'}) MERGE (p)-[:HAS_LEVEL]->(l);
MATCH (w:Weapon {name: 'Sword'}), (l:WeaponLevel) MERGE (w)-[:HAS_LEVEL]->(l);